[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino

upload_protocol = dfu
monitor_port = COM4
monitor_speed = 921600

lib_deps = 
    tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
